import React, { useEffect, useMemo, useState } from 'react';
import { createRoot } from 'react-dom/client';
import './styles.css';

type Job = { status: string; lastRun: number | null; error?: string; progress?: { message: string } };
type Channel = { id: string; title?: string; group?: string };
type Def = { key: string; label: string; route: string; fields?: string[] };
type Auto = { enabled: boolean; providers: Record<string, number>; providerLastRuns: Record<string, number> };
const providers = ['wsdeportes', 'cablevisionhd', 'tvporinternet2', 'tvenvivo2', 'chatytv', 'senalcolombia', 'vertvcable'];
const pretty = (p: string) => p === 'tvenvivo2' ? 'TVEnVivo2' : p;
const defs: Def[] = [
  ['movies', 'Películas', '/sync/movies', ['pages', 'replace']], ['series', 'Series', '/sync/series', ['pages', 'replace']], ['all', 'Todo (Películas + Series)', '/sync/all', ['pages', 'replace']],
  ['estrenoMovies', 'Estrenos Películas', '/sync/estrenos/movies', ['pages', 'replace']], ['estrenoSeries', 'Estrenos Series', '/sync/estrenos/series', ['pages', 'replace']], ['channels', 'TV en Vivo', '/sync/live'],
  ['popularMovies', 'Populares Películas', '/sync/popular/movies'], ['popularSeries', 'Populares Series', '/sync/popular/series'], ['home', 'Home cineby.sc', '/sync/home-bysc'], ['gnulahdHome', 'Home gnulahd', '/sync/gnulahd/home'],
  ['gnulahdMovies', 'Gnulahd Películas', '/sync/gnulahd/movies', ['pages', 'replace']], ['gnulahdSeries', 'Gnulahd Series', '/sync/gnulahd/series', ['pages', 'replace']], ['gnulahdAnime', 'Gnulahd Anime', '/sync/gnulahd/anime', ['pages', 'replace']],
  ['fetchDetails', 'Fetch Details', '/sync/fetch-details'], ['refreshAll', 'Refresh All Canales', '/live/channels/refresh-all'], ['refreshExpired', 'Refresh Expired', '/live/channels/refresh-expired'], ['importM3U', 'Importar M3U', '/sync/live/import', ['m3u']]
].map(([key, label, route, fields]) => ({ key: key as string, label: label as string, route: route as string, fields: fields as string[] | undefined }));
const fmt = (v?: number | null) => v ? new Date(v).toLocaleString('es-CO', { day: '2-digit', month: '2-digit', hour: '2-digit', minute: '2-digit' }) : 'Sin ejecutar';

function App() {
  const [status, setStatus] = useState<Record<string, Job>>({});
  const [processLogs, setProcessLogs] = useState<Record<string, string[]>>({});
  const [auto, setAuto] = useState<Auto>({ enabled: true, providers: {}, providerLastRuns: {} });
  const [threads, setThreads] = useState<Record<string, Record<string, string[]>>>({});
  const [oneLogs, setOneLogs] = useState<string[]>([]);
  const [collapsed, setCollapsed] = useState(false), [expanded, setExpanded] = useState<string[]>([]), [activeThreads, setActiveThreads] = useState(0), [providerRunning, setProviderRunning] = useState<string[]>([]);
  const [selected, setSelected] = useState<Def | null>(null), [params, setParams] = useState<Record<string, string | boolean>>({ pages: '1', replace: false, m3u: '' }), [executing, setExecuting] = useState(false);
  const [channels, setChannels] = useState<Channel[]>([]), [search, setSearch] = useState(''), [selectedIds, setSelectedIds] = useState<string[]>([]), [refreshing, setRefreshing] = useState(false), [message, setMessage] = useState(''), [editField, setEditField] = useState('title'), [editValue, setEditValue] = useState('');
  const [form, setForm] = useState({ provider: 'chatytv', param: '', title: '', logo: '', country: '', group: 'Canales TV' });
  const [jobs, setJobs] = useState<{ id: string; provider: string; param: string; state: string; message: string }[]>([]);

  useEffect(() => {
    fetch('/sync/status').then(r => r.json()).then(setStatus).catch(() => {});
    fetch('/sync/auto-refresh').then(r => r.json()).then(d => { setAuto(d); setActiveThreads(d.refreshProviderStatus?.activeCount || 0); }).catch(() => {});
    fetch('/live/channels?all=true&limit=1000').then(r => r.json()).then(d => setChannels(d.items || [])).catch(() => {});
    fetch('/sync/provider-logs').then(r => r.json()).then(data => { const grouped: Record<string, Record<string, string[]>> = {}; for (const [key, lines] of Object.entries(data)) { const parts = key.split(':'); if (parts[1] && parts[2]) grouped[parts[1]] = { ...(grouped[parts[1]] || {}), [parts.slice(2).join(':')]: lines as string[] }; } setThreads(grouped); }).catch(() => {});
    const loadProcessLogs = () => Promise.all(defs.map(async d => {
      try {
        const r = await fetch('/sync/detail/' + encodeURIComponent(d.key));
        if (r.ok) return [d.key, await r.json()] as const;
      } catch {}
      return [d.key, []] as const;
    })).then(entries => setProcessLogs(Object.fromEntries(entries)));
    loadProcessLogs();
    const logTimer = window.setInterval(loadProcessLogs, 3000);
    fetch('/sync/detail/refreshOne').then(r => r.json()).then(setOneLogs).catch(() => {});
    const es = new EventSource('/sync/events');
    es.onmessage = e => { const ev = JSON.parse(e.data); if (ev.type === 'status') setStatus(ev.status); if (ev.type === 'provider-status') { setActiveThreads(ev.active); if (ev.running && ev.provider) setThreads(v => ({ ...v, [ev.provider]: {} })); } if (ev.type === 'log' && ev.syncType === 'refreshOne') setOneLogs(v => [...v, ev.message].slice(-300)); if (ev.type === 'log' && ev.provider && ev.threadId) setThreads(v => ({ ...v, [ev.provider]: { ...(v[ev.provider] || {}), [ev.threadId]: [...((v[ev.provider] || {})[ev.threadId] || []), ev.message].slice(-199) } })); };
    return () => { es.close(); window.clearInterval(logTimer); };
  }, []);
  const filtered = useMemo(() => { const q = search.toLowerCase(); return channels.filter(c => !q || `${c.title || ''} ${c.id} ${c.group || ''}`.toLowerCase().includes(q)); }, [channels, search]);
  const running = Object.values(status).filter(x => x.status === 'running').length, completed = Object.values(status).filter(x => x.status === 'completed').length, failed = Object.values(status).filter(x => x.status === 'failed').length;
  const saveAuto = async (p: string, on: boolean) => { const focused = document.activeElement; const typed = focused instanceof HTMLInputElement && focused.type === 'number' ? Number(focused.value) : null; const next = { ...auto, providers: { ...auto.providers, [p]: typed !== null ? Math.max(1, typed) : (on ? (auto.providers[p] || 5) : 0) } }; setAuto(next); await fetch('/sync/auto-refresh', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(next) }); };
  const runProvider = async (p: string) => { setProviderRunning(v => [...v, p]); try { await fetch('/live/channels/refresh-provider/' + p, { method: 'POST' }); } finally { setProviderRunning(v => v.filter(x => x !== p)); } };
  const execute = async (d: Def) => { setExecuting(true); const body: Record<string, unknown> = {}; if (d.fields?.includes('pages')) { body.pages = String(params.pages || '1'); body.replace = params.replace === true; } if (d.fields?.includes('m3u')) body.content = params.m3u; try { const r = await fetch(d.route, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: Object.keys(body).length ? JSON.stringify(body) : undefined }); if (r.ok) setSelected(null); else setMessage('Error al iniciar ' + d.label + ' (' + r.status + ')'); } catch { setMessage('Error de red al iniciar ' + d.label); } finally { setExecuting(false); } };
  const refreshSelected = async () => { if (!selectedIds.length) return setMessage('Selecciona uno o varios canales'); setOneLogs([]); setRefreshing(true); setMessage('Refrescando canales...'); for (const id of selectedIds) await fetch('/live/channels/refresh', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ id }) }); setRefreshing(false); setMessage('Refresh terminado'); };
  const copyOneLogs = () => navigator.clipboard?.writeText(oneLogs.join('\n'));
  const updateField = async () => { if (!selectedIds.length) return setMessage('Selecciona uno o varios canales'); if (!editValue) return setMessage('Escribe un valor'); for (const id of selectedIds) await fetch('/live/channels/' + encodeURIComponent(id), { method: 'PATCH', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ [editField]: editField === 'online' ? editValue === 'true' : editValue }) }); setMessage('Campo actualizado correctamente'); };
  const add = async () => { if (!form.param || form.provider !== 'chatytv' && !form.title) return; const req = { ...form }, id = Date.now() + '-' + Math.random().toString(36).slice(2, 7); setJobs(v => [{ id, provider: req.provider, param: req.param, state: 'running', message: 'Agregando...' }, ...v].slice(0, 12)); setForm(v => ({ ...v, param: '', title: '', logo: '' })); const body: Record<string, string> = {}; Object.entries(req).forEach(([k, v]) => { if (k !== 'provider' && k !== 'param' && v) body[k] = v; }); try { const r = await fetch('/live/channels/add/' + req.provider + '/' + encodeURIComponent(req.param), { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(body) }); setJobs(v => v.map(j => j.id === id ? { ...j, state: r.ok ? 'success' : 'error', message: r.ok ? 'Terminado correctamente' : 'Error al agregar' } : j)); } catch { setJobs(v => v.map(j => j.id === id ? { ...j, state: 'error', message: 'Error de red' } : j)); } };

  return <div className={'shell ' + (collapsed ? 'sidebar-collapsed' : '')}><aside><div className="brand"><span className="brand-mark">◆</span>{!collapsed && <span>Panel de Sincronización</span>}<button className="collapse-button" onClick={() => setCollapsed(!collapsed)}>{collapsed ? '›' : '‹'}</button></div><nav><a className="active">▦ {!collapsed && <span>Resumen</span>}</a><a href="/player">◉ {!collapsed && <span>Canales</span>}</a><a href="/sync/detail/refreshProvider">▤ {!collapsed && <span>Registros</span>}</a></nav><div className="system">● {!collapsed && <><b>Sistema</b><small>Tiempo real</small></>}</div></aside><main>
    <header><div><span className="eyebrow">DASHBOARD</span><h1>Resumen operativo</h1><p>Control central de sincronizaciones y canales.</p></div><span className="live-pill">● Tiempo real</span></header>
    <section className="metrics"><Metric title="Procesos" value={defs.length} tone="purple" /><Metric title="Hilos activos" value={activeThreads || running} tone="green" /><Metric title="Completados" value={completed} tone="blue" /><Metric title="Con errores" value={failed} tone="red" /></section>
    <section className="dashboard-grid"><section className="panel processes"><PanelTitle title="Procesos" subtitle="Haz clic en una tarjeta para desplegar sus acciones" />{defs.map(d => <div className="process-item" key={d.key}><button className="process-title" onClick={() => setExpanded(v => v.includes(d.key) ? v.filter(x => x !== d.key) : [...v, d.key])}><span>{expanded.includes(d.key) ? '⌄' : '›'}</span><strong>{d.label}</strong><StatusBadge status={status[d.key]?.status || 'idle'} /></button>{expanded.includes(d.key) && <div className="process-actions"><small>{status[d.key]?.progress?.message || status[d.key]?.error || 'Listo para ejecutar'}</small><button className="action-button" onClick={() => { setSelected(d); setParams({ pages: '1', replace: false, m3u: '' }); }}>{d.fields ? '⚙ Parámetros' : '▶ Ejecutar'}</button><div className="process-log">{(processLogs[d.key] || []).slice(-12).map((line, i) => <div key={i}>{line}</div>)}{!(processLogs[d.key] || []).length && <span>Sin registros todavía</span>}</div></div>}</div>)}</section>
      <section className="panel provider-panel"><div className="panel-head"><div><h2>Refresh por proveedor</h2><span>Automático y ejecución manual en paralelo</span></div><span className="thread-counter">{activeThreads} hilos activos</span></div><div className="provider-list">{providers.map(p => <div className="provider-row" key={p}><span className={'dot ' + (auto.providers[p] ? 'active' : '')} /><strong>{pretty(p)}</strong><label className="mini-switch"><input type="checkbox" checked={Boolean(auto.providers[p])} onChange={e => saveAuto(p, e.target.checked)} /><span /></label><input className="interval" type="number" min="1" value={auto.providers[p] || ''} placeholder="min" onChange={e => saveAuto(p, Boolean(Number(e.target.value)))} /><small>{fmt(auto.providerLastRuns[p])}</small><button className="run-button" onClick={() => runProvider(p)} disabled={providerRunning.includes(p)}>{providerRunning.includes(p) ? '⟳' : '▶'}</button></div>)}</div>{providers.map(p => <ProviderLogs key={p} provider={p} threads={threads[p] || {}} />)}</section></section>
    <section className="panel add-card"><PanelTitle title="Agregar canales en vivo" subtitle="Puedes iniciar varias altas sin bloquear el formulario." /><div className="form-grid"><Field label="Proveedor"><select value={form.provider} onChange={e => setForm({ ...form, provider: e.target.value })}>{providers.map(p => <option key={p} value={p}>{pretty(p)}</option>)}</select></Field><Field label="Canal / Slug"><input value={form.param} onChange={e => setForm({ ...form, param: e.target.value })} placeholder="canal-sony-en-vivo-por-internet" /></Field><Field label="Título"><input value={form.title} onChange={e => setForm({ ...form, title: e.target.value })} /></Field><Field label="Logo URL"><input value={form.logo} onChange={e => setForm({ ...form, logo: e.target.value })} /></Field><Field label="País"><input value={form.country} onChange={e => setForm({ ...form, country: e.target.value.toUpperCase() })} /></Field><Field label="Grupo"><input value={form.group} onChange={e => setForm({ ...form, group: e.target.value })} /></Field></div><button className="primary-button" onClick={add}>＋ Agregar canal</button><div className="channel-jobs">{jobs.map(j => <div className="channel-job" key={j.id}><span className={j.state === 'running' ? 'spinner' : j.state === 'success' ? 'ok-mark' : 'error-mark'}>{j.state === 'running' ? '⟳' : j.state === 'success' ? '✓' : '!'}</span><b>{pretty(j.provider)}</b><span>{j.param}</span><small>{j.message}</small></div>)}</div></section>
    <section className="panel channel-actions"><PanelTitle title="Actualizar canales" subtitle="Busca, selecciona y actualiza solo el campo que necesites." /><input className="channel-search" value={search} onChange={e => setSearch(e.target.value)} placeholder="⌕ Buscar por nombre, ID o grupo..." /><select className="channel-multi" multiple value={selectedIds} onChange={e => setSelectedIds(Array.from(e.target.selectedOptions).map(o => o.value))}>{filtered.map(c => <option key={c.id} value={c.id}>{c.title || c.id} · {c.group || 'Sin grupo'}</option>)}</select><div className="selection-toolbar"><span>{selectedIds.length} seleccionados</span><button className="primary-button" onClick={refreshSelected} disabled={refreshing}>{refreshing ? '⟳ Refrescando...' : '↻ Refresh seleccionados'}</button></div><div className="edit-inline"><select value={editField} onChange={e => setEditField(e.target.value)}><option value="title">Título</option><option value="logo">Logo URL</option><option value="country">País</option><option value="group">Grupo</option><option value="online">Online</option><option value="refreshUrl">Refresh URL</option><option value="refreshOption">Parámetro</option></select><input value={editValue} onChange={e => setEditValue(e.target.value)} placeholder="Valor del campo seleccionado" /><button className="secondary-button" onClick={updateField}>✎ Actualizar campo</button></div>{message && <div className="form-message">{message}</div>}</section>
    <section className="panel refresh-one-log-card"><div className="one-log-head"><div><h2>Log de actualización de canales</h2><span>{oneLogs.length ? `${oneLogs.length} registros` : 'Sin ejecución reciente'}</span></div><button className="copy-log" onClick={copyOneLogs} disabled={!oneLogs.length}>Copiar log</button></div><div className="one-log-body">{oneLogs.length ? oneLogs.map((line, i) => <div key={i}>{line}</div>) : <span>Selecciona canales y presiona “Refresh seleccionados” para ver el progreso.</span>}</div></section>
  </main>{selected && <Modal def={selected} params={params} setParams={setParams} close={() => setSelected(null)} execute={() => execute(selected)} executing={executing} />}</div>;
}
function Field({ label, children }: { label: string; children: React.ReactNode }) { return <label className="field"><span>{label}</span>{children}</label>; }
function PanelTitle({ title, subtitle }: { title: string; subtitle: string }) { return <div className="panel-head"><div><h2>{title}</h2><span>{subtitle}</span></div></div>; }
function Metric({ title, value, tone }: { title: string; value: number; tone: string }) { return <div className={'metric ' + tone}><span>{title}</span><b>{value}</b><small>Actualizado en vivo</small></div>; }
function StatusBadge({ status }: { status: string }) { return <span className={'badge ' + status}>{status === 'running' ? 'Ejecutando' : status === 'completed' ? 'Completado' : status === 'failed' ? 'Error' : 'Listo'}</span>; }
function Modal({ def, params, setParams, close, execute, executing }: { def: Def; params: Record<string, string | boolean>; setParams: React.Dispatch<React.SetStateAction<Record<string, string | boolean>>>; close: () => void; execute: () => void; executing: boolean }) { return <div className="modal-backdrop" onClick={close}><div className="modal-card" onClick={e => e.stopPropagation()}><button className="modal-close" onClick={close}>×</button><h2>{def.label}</h2>{def.fields?.includes('pages') && <><Field label="Páginas"><input type="number" min="1" value={String(params.pages)} onChange={e => setParams(v => ({ ...v, pages: e.target.value }))} /></Field><label className="switch-row"><input type="checkbox" checked={params.replace === true} onChange={e => setParams(v => ({ ...v, replace: e.target.checked }))} /> Reemplazar datos</label></>}{def.fields?.includes('m3u') && <Field label="Contenido M3U"><textarea rows={8} value={String(params.m3u || '')} onChange={e => setParams(v => ({ ...v, m3u: e.target.value }))} /></Field>}<button className="primary-button" onClick={execute} disabled={executing}>{executing ? '⟳ Ejecutando...' : '▶ Ejecutar'}</button></div></div>; }
function ProviderLogs({ provider, threads }: { provider: string; threads: Record<string, string[]> }) { const ids = Object.keys(threads); const [active, setActive] = useState(''); const current = active && threads[active] ? active : ids[ids.length - 1]; const copy = () => navigator.clipboard?.writeText((threads[current] || []).join('\n')); return <details className="provider-log"><summary>Logs de {pretty(provider)} <span>{ids.length} hilos</span></summary>{ids.length ? <><div className="thread-toolbar"><div className="thread-tabs">{ids.map((id, i) => { const hasError = threads[id].some(line => /error|fall[oó]|failed|exception/i.test(line)); return <button className={`${id === current ? 'active ' : ''}${hasError ? 'failed' : 'ok'}`} onClick={() => setActive(id)} key={id}>Hilo {i + 1}<span className="thread-state">{hasError ? '!' : '✓'}</span></button>; })}</div><button className="copy-log" onClick={copy}>Copiar</button></div><div className="thread-log">{threads[current].map((line, i) => <div key={i}>{line}</div>)}</div></> : <div className="log-empty">Sin ejecuciones todavía</div>}</details>; }
createRoot(document.getElementById('root')!).render(<React.StrictMode><App /></React.StrictMode>);
