import React, { useEffect, useMemo, useRef, useState } from 'react';
import { createRoot } from 'react-dom/client';
import './styles.css';

type Job = { status: string; lastRun: number | null; error?: string; progress?: { message: string } };
type Channel = { id: string; title?: string; group?: string };
type Def = { key: string; label: string; route: string; fields?: string[] };
type Auto = { enabled: boolean; providers: Record<string, number>; providerLastRuns: Record<string, number> };
type GAutoTask = { enabled?: boolean; intervalHours?: number; pages?: string; lastRunAt?: number };
type GAuto = { tasks: Partial<Record<string, GAutoTask>> };
type GItem = { id: string; title: string; poster?: string; year?: number; type?: string };
type Bk = { id: string; createdAt: number; counts: Record<string, number> };
type M3uCh = { idx: number; title: string; group: string; logo: string; country: string; url: string };
const backupCols: [string, string][] = [['movies', 'Películas'], ['series', 'Series'], ['channels', 'Canales'], ['popular-movies', 'Populares (M)'], ['popular-series', 'Populares (S)'], ['estreno-movies', 'Estrenos (M)'], ['estreno-series', 'Estrenos (S)'], ['gnulahd-movies', 'GNULA Películas'], ['gnulahd-series', 'GNULA Series'], ['gnulahd-anime', 'GNULA Anime']];
const providers = ['wsdeportes', 'cablevisionhd', 'tvporinternet2', 'tvenvivo2', 'chatytv', 'senalcolombia', 'vertvcable'];
const gnulahdTasks = ['gnulahdHome', 'gnulahdMovies', 'gnulahdSeries', 'gnulahdAnime'];
const gnulahdTaskNames: Record<string, string> = { gnulahdHome: 'Home', gnulahdMovies: 'Películas', gnulahdSeries: 'Series', gnulahdAnime: 'Anime' };
const gnulahdTaskKinds: Record<string, string> = { gnulahdMovies: 'movies', gnulahdSeries: 'series', gnulahdAnime: 'anime', gnulahdHome: 'home' };
const pretty = (p: string) => p === 'tvenvivo2' ? 'TVEnVivo2' : p;
const defs: Def[] = [
  ['movies', 'Películas', '/sync/movies', ['pages', 'replace']], ['series', 'Series', '/sync/series', ['pages', 'replace']], ['all', 'Todo (Películas + Series)', '/sync/all', ['pages', 'replace']],
  ['estrenoMovies', 'Estrenos Películas', '/sync/estrenos/movies', ['pages', 'replace']], ['estrenoSeries', 'Estrenos Series', '/sync/estrenos/series', ['pages', 'replace']], ['channels', 'TV en Vivo', '/sync/live'],
  ['popularMovies', 'Populares Películas', '/sync/popular/movies'], ['popularSeries', 'Populares Series', '/sync/popular/series'], ['home', 'Home cineby.sc', '/sync/home-bysc'], ['gnulahdHome', 'Home gnulahd', '/sync/gnulahd/home'],
  ['gnulahdMovies', 'Gnulahd Películas', '/sync/gnulahd/movies', ['pages', 'replace']], ['gnulahdSeries', 'Gnulahd Series', '/sync/gnulahd/series', ['pages', 'replace']], ['gnulahdAnime', 'Gnulahd Anime', '/sync/gnulahd/anime', ['pages', 'replace']],
  ['fetchDetails', 'Fetch Details', '/sync/fetch-details'], ['refreshAll', 'Refresh All Canales', '/live/channels/refresh-all'], ['refreshExpired', 'Refresh Expired', '/live/channels/refresh-expired'], ['importM3U', 'Importar M3U', '/sync/live/import']
].map(([key, label, route, fields]) => ({ key: key as string, label: label as string, route: route as string, fields: fields as string[] | undefined }));
const fmt = (v?: number | null) => v ? new Date(v).toLocaleString('es-CO', { day: '2-digit', month: '2-digit', hour: '2-digit', minute: '2-digit' }) : 'Sin ejecutar';

function App() {
  const [status, setStatus] = useState<Record<string, Job>>({});
  const [processLogs, setProcessLogs] = useState<Record<string, string[]>>({});
  const [processMessages, setProcessMessages] = useState<Record<string, string>>({});
  const [auto, setAuto] = useState<Auto>({ enabled: true, providers: {}, providerLastRuns: {} });
  const [gauto, setGauto] = useState<GAuto>({ tasks: {} });
  const [threads, setThreads] = useState<Record<string, Record<string, string[]>>>({});
  const [oneLogs, setOneLogs] = useState<string[]>([]);
  const [collapsed, setCollapsed] = useState(false), [expanded, setExpanded] = useState<string[]>([]), [activeThreads, setActiveThreads] = useState(0), [providerRunning, setProviderRunning] = useState<string[]>([]);
  const [selected, setSelected] = useState<Def | null>(null), [params, setParams] = useState<Record<string, string | boolean>>({ pages: '1-20', replace: false, m3u: '' }), [executing, setExecuting] = useState(false);
  const [channels, setChannels] = useState<Channel[]>([]), [search, setSearch] = useState(''), [selectedIds, setSelectedIds] = useState<string[]>([]), [refreshing, setRefreshing] = useState(false), [message, setMessage] = useState(''), [editField, setEditField] = useState('title'), [editValue, setEditValue] = useState('');
  const [form, setForm] = useState({ provider: 'chatytv', param: '', title: '', logo: '', country: '', group: 'Canales TV' });
  const [jobs, setJobs] = useState<{ id: string; provider: string; param: string; state: string; message: string }[]>([]);
  const [gitems, setGitems] = useState<GItem[]>([]);
  const [gitemKind, setGitemKind] = useState('movies');
  const [gitemId, setGitemId] = useState('');
  const [gnewSlug, setGnewSlug] = useState('');
  const [itemLogs, setItemLogs] = useState<string[]>([]);
  const [backups, setBackups] = useState<Bk[]>([]);
  const [bkId, setBkId] = useState('');
  const [bkFile, setBkFile] = useState<File | null>(null);
  const [bkCols, setBkCols] = useState<string[]>(backupCols.map(([k]) => k));
  const [bkMsg, setBkMsg] = useState('');
  const [bkBusy, setBkBusy] = useState(false);
  const [m3uUrl, setM3uUrl] = useState('');
  const [m3uToken, setM3uToken] = useState('');
  const [m3uPreview, setM3uPreview] = useState<M3uCh[]>([]);
  const [m3uSearch, setM3uSearch] = useState('');
  const [m3uSel, setM3uSel] = useState<number[]>([]);
  const [m3uMsg, setM3uMsg] = useState('');
  const [m3uLoading, setM3uLoading] = useState(false);

  useEffect(() => {
    const loadStatus = () => fetch('/sync/status').then(r => r.json()).then(setStatus).catch(() => {});
    loadStatus();
    const statusTimer = window.setInterval(loadStatus, 3000);
    fetch('/sync/auto-refresh').then(r => r.json()).then(d => { setAuto(d); setActiveThreads(d.refreshProviderStatus?.activeCount || 0); }).catch(() => {});
    fetch('/sync/gnulahd/auto').then(r => r.json()).then(d => setGauto(d)).catch(() => {});
    fetch('/live/channels?all=true&limit=1000').then(r => r.json()).then(d => setChannels(d.items || [])).catch(() => {});
    fetch('/sync/provider-logs').then(r => r.json()).then(data => { const grouped: Record<string, Record<string, string[]>> = {}; for (const [key, lines] of Object.entries(data)) { const parts = key.split(':'); if (parts[1] && parts[2]) grouped[parts[1]] = { ...(grouped[parts[1]] || {}), [parts.slice(2).join(':')]: lines as string[] }; } setThreads(grouped); }).catch(() => {});
    const loadProcessLogs = () => Promise.all(defs.map(async d => {
      try {
        const r = await fetch('/sync/detail/' + encodeURIComponent(d.key));
        if (r.ok) return [d.key, await r.json()] as const;
      } catch {}
      return [d.key, []] as const;
    })).then(entries => setProcessLogs(Object.fromEntries(entries)));
    loadProcessLogs();
    const logTimer = window.setInterval(loadProcessLogs, 3000);
    const loadItemLogs = () => fetch('/sync/detail/gnulahdItem').then(r => r.json()).then(setItemLogs).catch(() => {});
    loadItemLogs();
    const itemLogTimer = window.setInterval(loadItemLogs, 3000);
    fetch('/sync/detail/refreshOne').then(r => r.json()).then(setOneLogs).catch(() => {});
    const es = new EventSource('/sync/events');
    es.onmessage = e => { const ev = JSON.parse(e.data); if (ev.type === 'status') setStatus(ev.status); if (ev.type === 'provider-status') { setActiveThreads(ev.active); if (ev.running && ev.provider) setThreads(v => ({ ...v, [ev.provider]: {} })); } if (ev.type === 'log' && ev.syncType === 'refreshOne') setOneLogs(v => [...v, ev.message].slice(-300)); if (ev.type === 'log' && ev.syncType === 'gnulahdItem') setItemLogs(v => [...v, ev.message].slice(-300)); if (ev.type === 'log' && ev.provider && ev.threadId) setThreads(v => ({ ...v, [ev.provider]: { ...(v[ev.provider] || {}), [ev.threadId]: [...((v[ev.provider] || {})[ev.threadId] || []), ev.message].slice(-199) } })); };
    return () => { es.close(); window.clearInterval(logTimer); window.clearInterval(statusTimer); window.clearInterval(itemLogTimer); };
  }, []);
  const loadGitems = () => fetch('/sync/gnulahd/items?kind=' + gitemKind).then(r => r.json()).then(d => { setGitems(d.items || []); setGitemId(v => (d.items || []).some((i: GItem) => i.id === v) ? v : ''); }).catch(() => {});
  useEffect(() => { loadGitems(); }, [gitemKind]);
  const loadBackups = () => fetch('/sync/backups').then(r => r.json()).then(d => setBackups(d.items || [])).catch(() => {});
  useEffect(() => { loadBackups(); }, []);
  const runBackup = async () => { setBkBusy(true); setBkMsg(''); try { const r = await fetch('/sync/backups', { method: 'POST' }); const d = await r.json(); if (!r.ok) throw new Error(d.error || 'Error HTTP ' + r.status); setBkMsg('✔ Backup creado: ' + backupCols.map(([k, l]) => `${l}: ${d.counts?.[k] ?? 0}`).join(' · ')); loadBackups(); } catch (e: any) { setBkMsg('✖ ' + (e.message || 'Error')); } finally { setBkBusy(false); } };
  const loadM3U = async () => { if (!m3uUrl.trim()) return setM3uMsg('Escribe la URL de la lista M3U'); setM3uLoading(true); setM3uMsg(''); try { const r = await fetch('/sync/live/m3u-preview', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ url: m3uUrl.trim() }) }); const d = await r.json(); if (!r.ok) throw new Error(d.error || 'Error HTTP ' + r.status); setM3uToken(d.token || ''); setM3uPreview(d.channels || []); setM3uSel([]); setM3uSearch(''); setM3uMsg('✔ ' + (d.count ?? 0) + ' canales encontrados. Marca los que quieras importar.'); } catch (e: any) { setM3uMsg('✖ ' + (e.message || 'Error')); } finally { setM3uLoading(false); } };
  const doImportM3U = async () => { if (!m3uToken || !m3uSel.length) return setM3uMsg('Carga una lista y selecciona al menos un canal'); setM3uLoading(true); setM3uMsg(''); try { const r = await fetch('/sync/live/import', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ token: m3uToken, selected: m3uSel }) }); const d = await r.json(); if (!r.ok) throw new Error(d.error || 'Error HTTP ' + r.status); setStatus(v => ({ ...v, importM3U: { ...(v.importM3U || { lastRun: null }), status: 'running', progress: { current: 0, message: 'Solicitud aceptada; proceso en segundo plano' } } })); setProcessMessages(v => ({ ...v, importM3U: '✅ Solicitud aceptada; proceso en segundo plano' })); setM3uMsg('✔ Importación iniciada con ' + m3uSel.length + ' canales seleccionados.'); } catch (e: any) { setM3uMsg('✖ ' + (e.message || 'Error')); } finally { setM3uLoading(false); } };
  const toggleBkCol = (k: string) => setBkCols(v => v.includes(k) ? v.filter(x => x !== k) : [...v, k]);
  const setAllBkCols = (on: boolean) => setBkCols(on ? backupCols.map(([k]) => k) : []);
  const doRestore = async () => { if (!bkId && !bkFile) return setBkMsg('Selecciona un backup de la lista o un archivo'); if (!bkCols.length) return setBkMsg('Marca al menos una colección (o "Restaurar todo")'); setBkBusy(true); setBkMsg(''); try { const body: Record<string, unknown> = {}; if (bkFile) { body.file = JSON.parse(await bkFile.text()); } else { body.id = bkId; } if (bkCols.length !== backupCols.length) body.collections = bkCols; const r = await fetch('/sync/backups/restore', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(body) }); const d = await r.json(); if (!r.ok) throw new Error(d.error || 'Error HTTP ' + r.status); setBkMsg('✔ Restaurado: ' + Object.entries(d.counts || {}).map(([k, v]) => `${backupCols.find(([c]) => c === k)?.[1] || k}: ${v}`).join(' · ')); } catch (e: any) { setBkMsg('✖ ' + (e.message || 'Error')); } finally { setBkBusy(false); } };
  const runItem = async () => { if (!gitemId) return; setItemLogs([]); setGnewSlug(''); await fetch('/sync/gnulahd/item', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ id: gitemId }) }).catch(() => {}); };
  const addItem = async () => { if (!gnewSlug.trim()) return; setItemLogs([]); setGitemId(''); await fetch('/sync/gnulahd/item', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ kind: gitemKind, slug: gnewSlug.trim() }) }).catch(() => {}); };
  const copyItemLogs = () => navigator.clipboard?.writeText(itemLogs.join('\n'));
  const itemRunning = status['gnulahdItem']?.status === 'running';
  const filtered = useMemo(() => { const q = search.toLowerCase(); return channels.filter(c => !q || `${c.title || ''} ${c.id} ${c.group || ''}`.toLowerCase().includes(q)); }, [channels, search]);
  const running = Object.values(status).filter(x => x.status === 'running').length, completed = Object.values(status).filter(x => x.status === 'completed').length, failed = Object.values(status).filter(x => x.status === 'failed').length;
  const saveAuto = async (p: string, on: boolean) => { const focused = document.activeElement; const typed = focused instanceof HTMLInputElement && focused.type === 'number' ? Number(focused.value) : null; const next = { ...auto, providers: { ...auto.providers, [p]: typed !== null ? Math.max(1, typed) : (on ? (auto.providers[p] || 5) : 0) } }; setAuto(next); await fetch('/sync/auto-refresh', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(next) }); };
  const saveGAuto = async (key: string, enabled: boolean, hours?: number) => { const prev = gauto.tasks[key] || {}; const current = { enabled, intervalHours: hours ?? prev.intervalHours ?? 12, pages: prev.pages || (key === 'gnulahdHome' ? undefined : '1-10') }; const next: GAuto = { tasks: { ...gauto.tasks, [key]: current } }; setGauto(next); await fetch('/sync/gnulahd/auto', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ tasks: { [key]: current } }) }).catch(() => {}); };
  const runProvider = async (p: string) => { setProviderRunning(v => [...v, p]); try { await fetch('/live/channels/refresh-provider/' + p, { method: 'POST' }); } finally { setProviderRunning(v => v.filter(x => x !== p)); } };
  const execute = async (d: Def) => { setExecuting(true); setProcessMessages(v => ({ ...v, [d.key]: 'Enviando solicitud...' })); const body: Record<string, unknown> = {}; if (d.fields?.includes('pages')) { body.pages = String(params.pages || '1'); body.replace = params.replace === true; } try { const r = await fetch(d.route, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(body) }); if (r.ok) { setStatus(v => ({ ...v, [d.key]: { ...(v[d.key] || { lastRun: null }), status: 'running', progress: { current: 0, message: 'Solicitud aceptada; proceso en segundo plano' } } })); setProcessMessages(v => ({ ...v, [d.key]: '✅ Solicitud aceptada; proceso en segundo plano' })); setSelected(null); } else { setProcessMessages(v => ({ ...v, [d.key]: '❌ Error HTTP ' + r.status })); } } catch { setProcessMessages(v => ({ ...v, [d.key]: '❌ Error de red al iniciar' })); } finally { setExecuting(false); } };
  const refreshSelected = async () => { if (!selectedIds.length) return setMessage('Selecciona uno o varios canales'); setOneLogs([]); setRefreshing(true); setMessage('Refrescando canales...'); for (const id of selectedIds) await fetch('/live/channels/refresh', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ id }) }); setRefreshing(false); setMessage('Refresh terminado'); };
  const copyOneLogs = () => navigator.clipboard?.writeText(oneLogs.join('\n'));
  const updateField = async () => { if (!selectedIds.length) return setMessage('Selecciona uno o varios canales'); if (!editValue) return setMessage('Escribe un valor'); for (const id of selectedIds) await fetch('/live/channels/' + encodeURIComponent(id), { method: 'PATCH', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ [editField]: editField === 'online' ? editValue === 'true' : editValue }) }); setMessage('Campo actualizado correctamente'); };
  const add = async () => { if (!form.param || form.provider !== 'chatytv' && !form.title) return; const req = { ...form }, id = Date.now() + '-' + Math.random().toString(36).slice(2, 7); setJobs(v => [{ id, provider: req.provider, param: req.param, state: 'running', message: 'Agregando...' }, ...v].slice(0, 12)); setForm(v => ({ ...v, param: '', title: '', logo: '' })); const body: Record<string, string> = {}; Object.entries(req).forEach(([k, v]) => { if (k !== 'provider' && k !== 'param' && v) body[k] = v; }); try { const r = await fetch('/live/channels/add/' + req.provider + '/' + encodeURIComponent(req.param), { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(body) }); setJobs(v => v.map(j => j.id === id ? { ...j, state: r.ok ? 'success' : 'error', message: r.ok ? 'Terminado correctamente' : 'Error al agregar' } : j)); } catch { setJobs(v => v.map(j => j.id === id ? { ...j, state: 'error', message: 'Error de red' } : j)); } };

  return <div className={'shell ' + (collapsed ? 'sidebar-collapsed' : '')}><aside><div className="brand"><span className="brand-mark">◆</span>{!collapsed && <span>Panel de Sincronización</span>}<button className="collapse-button" onClick={() => setCollapsed(!collapsed)}>{collapsed ? '›' : '‹'}</button></div><nav><a className="active">▦ {!collapsed && <span>Resumen</span>}</a><a href="/player">◉ {!collapsed && <span>Canales</span>}</a><a href="/sync/detail/refreshProvider">▤ {!collapsed && <span>Registros</span>}</a></nav><div className="system">● {!collapsed && <><b>Sistema</b><small>Tiempo real</small></>}</div></aside><main>
    <header><div><span className="eyebrow">DASHBOARD</span><h1>Resumen operativo</h1><p>Control central de sincronizaciones y canales.</p></div><span className="live-pill">● Tiempo real</span></header>
    <section className="metrics"><Metric title="Procesos" value={defs.length} tone="purple" /><Metric title="Hilos activos" value={activeThreads || running} tone="green" /><Metric title="Completados" value={completed} tone="blue" /><Metric title="Con errores" value={failed} tone="red" /></section>
    <section className="dashboard-grid"><section className="panel processes"><PanelTitle title="Procesos" subtitle="Haz clic en una tarjeta para desplegar sus acciones" />{defs.map(d => <div className="process-item" key={d.key}><button type="button" className="process-title" onClick={() => setExpanded(v => v.includes(d.key) ? v.filter(x => x !== d.key) : [...v, d.key])}><span>{expanded.includes(d.key) ? '⌄' : '›'}</span><strong>{d.label}</strong><StatusBadge status={status[d.key]?.status || 'idle'} /></button>{expanded.includes(d.key) && <div className="process-actions"><small>{status[d.key]?.progress?.message || status[d.key]?.error || processMessages[d.key] || 'Listo para ejecutar'}</small>{gnulahdTasks.includes(d.key) && <div className="ga-row"><span className="ga-label">Auto-sync</span><label className="mini-switch"><input type="checkbox" checked={Boolean(gauto.tasks[gnulahdTaskKinds[d.key]]?.enabled)} onChange={e => saveGAuto(gnulahdTaskKinds[d.key], e.target.checked)} /><span /></label><input className="interval" type="number" min="0.5" step="0.5" value={gauto.tasks[gnulahdTaskKinds[d.key]]?.intervalHours ?? ''} placeholder="horas" onChange={e => saveGAuto(gnulahdTaskKinds[d.key], Boolean(gauto.tasks[gnulahdTaskKinds[d.key]]?.enabled), Number(e.target.value))} /><small>{fmt(gauto.tasks[gnulahdTaskKinds[d.key]]?.lastRunAt)}</small></div>}{d.key === 'importM3U' ? <M3UImportPanel url={m3uUrl} setUrl={setM3uUrl} preview={m3uPreview} sel={m3uSel} setSel={setM3uSel} search={m3uSearch} setSearch={setM3uSearch} msg={m3uMsg} loading={m3uLoading} onLoad={loadM3U} onImport={doImportM3U} /> : <button type="button" className="action-button" onClick={e => { e.stopPropagation(); if (d.fields) { setSelected(d); setParams({ pages: '1-20', replace: false, m3u: '' }); } else void execute(d); }}>{d.fields ? '⚙ Parámetros' : '▶ Ejecutar'}</button>}<div className="process-log">{(processLogs[d.key] || []).map((line, i) => <div key={i}>{line}</div>)}{!(processLogs[d.key] || []).length && <span>{processMessages[d.key] || 'Sin registros todavía'}</span>}</div></div>}</div>)}</section>
      <section className="panel provider-panel"><div className="panel-head"><div><h2>Refresh por proveedor</h2><span>Automático y ejecución manual en paralelo</span></div><span className="thread-counter">{activeThreads} hilos activos</span></div><div className="provider-list">{providers.map(p => <div className="provider-row" key={p}><span className={'dot ' + (auto.providers[p] ? 'active' : '')} /><strong>{pretty(p)}</strong><label className="mini-switch"><input type="checkbox" checked={Boolean(auto.providers[p])} onChange={e => saveAuto(p, e.target.checked)} /><span /></label><input className="interval" type="number" min="1" value={auto.providers[p] || ''} placeholder="min" onChange={e => saveAuto(p, Boolean(Number(e.target.value)))} /><small>{fmt(auto.providerLastRuns[p])}</small><button className="run-button" onClick={() => runProvider(p)} disabled={providerRunning.includes(p)}>{providerRunning.includes(p) ? '⟳' : '▶'}</button></div>)}</div>{providers.map(p => <ProviderLogs key={p} provider={p} threads={threads[p] || {}} />)}</section></section>
    <section className="panel add-card"><PanelTitle title="Agregar canales en vivo" subtitle="Puedes iniciar varias altas sin bloquear el formulario." /><div className="form-grid"><Field label="Proveedor"><select value={form.provider} onChange={e => setForm({ ...form, provider: e.target.value })}>{providers.map(p => <option key={p} value={p}>{pretty(p)}</option>)}</select></Field><Field label="Canal / Slug"><input value={form.param} onChange={e => setForm({ ...form, param: e.target.value })} placeholder="canal-sony-en-vivo-por-internet" /></Field><Field label="Título"><input value={form.title} onChange={e => setForm({ ...form, title: e.target.value })} /></Field><Field label="Logo URL"><input value={form.logo} onChange={e => setForm({ ...form, logo: e.target.value })} /></Field><Field label="País"><input value={form.country} onChange={e => setForm({ ...form, country: e.target.value.toUpperCase() })} /></Field><Field label="Grupo"><input value={form.group} onChange={e => setForm({ ...form, group: e.target.value })} /></Field></div><button className="primary-button" onClick={add}>＋ Agregar canal</button><div className="channel-jobs">{jobs.map(j => <div className="channel-job" key={j.id}><span className={j.state === 'running' ? 'spinner' : j.state === 'success' ? 'ok-mark' : 'error-mark'}>{j.state === 'running' ? '⟳' : j.state === 'success' ? '✓' : '!'}</span><b>{pretty(j.provider)}</b><span>{j.param}</span><small>{j.message}</small></div>)}</div></section>
    <section className="panel channel-actions"><PanelTitle title="Actualizar canales" subtitle="Busca, selecciona y actualiza solo el campo que necesites." /><input className="channel-search" value={search} onChange={e => setSearch(e.target.value)} placeholder="⌕ Buscar por nombre, ID o grupo..." /><select className="channel-multi" multiple value={selectedIds} onChange={e => setSelectedIds(Array.from(e.target.selectedOptions).map(o => o.value))}>{filtered.map(c => <option key={c.id} value={c.id}>{c.title || c.id} · {c.group || 'Sin grupo'}</option>)}</select><div className="selection-toolbar"><span>{selectedIds.length} seleccionados</span><button className="primary-button" onClick={refreshSelected} disabled={refreshing}>{refreshing ? '⟳ Refrescando...' : '↻ Refresh seleccionados'}</button></div><div className="edit-inline"><select value={editField} onChange={e => setEditField(e.target.value)}><option value="title">Título</option><option value="logo">Logo URL</option><option value="country">País</option><option value="group">Grupo</option><option value="online">Online</option><option value="refreshUrl">Refresh URL</option><option value="refreshOption">Parámetro</option></select><input value={editValue} onChange={e => setEditValue(e.target.value)} placeholder="Valor del campo seleccionado" /><button className="secondary-button" onClick={updateField}>✎ Actualizar campo</button></div>{message && <div className="form-message">{message}</div>}</section>
    <section className="panel refresh-one-log-card"><div className="one-log-head"><div><h2>Log de actualización de canales</h2><span>{oneLogs.length ? `${oneLogs.length} registros` : 'Sin ejecución reciente'}</span></div><button className="copy-log" onClick={copyOneLogs} disabled={!oneLogs.length}>Copiar log</button></div><div className="one-log-body">{oneLogs.length ? oneLogs.map((line, i) => <div key={i}>{line}</div>) : <span>Selecciona canales y presiona “Refresh seleccionados” para ver el progreso.</span>}</div></section>
    <section className="panel backup-card"><PanelTitle title="Backup de base de datos" subtitle="Crea un respaldo completo, descarga el último o restaura todo o solo las colecciones que elijas." /><div className="bk-row"><button className="primary-button" onClick={runBackup} disabled={bkBusy}>{bkBusy ? '⟳ Trabajando...' : '💾 Realizar backup'}</button><a className="bk-download" href="/sync/backups/download" download={backups[0] ? 'backup-' + backups[0].createdAt + '.json' : 'backup.json'}>⬇ Descargar último backup</a></div><div className="bk-cols-head"><strong>Restaurar</strong><small>Elige la fuente (backup de la BD o el archivo descargado) y qué colecciones restaurar.</small></div><div className="gitem-row"><Field label="Backup disponible (BD)"><select value={bkId} onChange={e => { setBkId(e.target.value); setBkFile(null); }}><option value="">— Selecciona un backup —</option>{backups.map(b => <option key={b.id} value={b.id}>{new Date(b.createdAt).toLocaleString('es-CO', { day: '2-digit', month: '2-digit', hour: '2-digit', minute: '2-digit' })} · {Object.values(b.counts).reduce((a, c) => a + c, 0)} items</option>)}</select></Field><Field label="O archivo descargado (.json)"><input type="file" accept=".json,application/json" onChange={e => { setBkFile(e.target.files?.[0] || null); setBkId(''); }} /></Field></div><div className="bk-cols"><label className="bk-col"><input type="checkbox" checked={bkCols.length === backupCols.length} onChange={e => setAllBkCols(e.target.checked)} /> Restaurar todo</label>{backupCols.map(([k, l]) => <label className="bk-col" key={k}><input type="checkbox" checked={bkCols.includes(k)} onChange={() => toggleBkCol(k)} /> {l}</label>)}</div><div className="bk-row"><button className="primary-button" onClick={doRestore} disabled={bkBusy || (!bkId && !bkFile)}>{bkBusy ? '⟳ Trabajando...' : '↺ Restaurar'}</button><button className="secondary-button" onClick={loadBackups} disabled={bkBusy}>↻ Recargar backups</button></div>{bkMsg && <div className="form-message">{bkMsg}</div>}</section>
    <section className="panel gitem-card"><PanelTitle title="Sincronizar ítem GNULA" subtitle="Selecciona un slug de la base de datos o agrega uno nuevo; los pasos y los servidores de cada proveedor se registran en vivo." /><div className="gitem-row"><Field label="Tipo"><select value={gitemKind} onChange={e => { setGitemKind(e.target.value); setGitemId(''); }}><option value="movies">Películas</option><option value="series">Series</option><option value="anime">Anime</option></select></Field><button className="icon-button" title="Recargar lista" onClick={loadGitems}>↻</button></div><div className="gitem-row"><Field label="Slug en base de datos"><Combobox options={gitems} value={gitemId} onChange={setGitemId} placeholder="Escribe para buscar por título o slug..." /></Field><button className="primary-button" onClick={runItem} disabled={!gitemId || itemRunning}>{itemRunning ? '⟳ Sincronizando...' : '▶ Sincronizar'}</button></div><div className="gitem-divider">＋ Agregar un ítem nuevo por slug (no necesita estar en BD)</div><div className="gitem-row"><Field label="Slug nuevo"><input value={gnewSlug} onChange={e => setGnewSlug(e.target.value)} placeholder="ej: silo" onKeyDown={e => { if (e.key === 'Enter') addItem(); }} /></Field><button className="primary-button" onClick={addItem} disabled={!gnewSlug.trim() || itemRunning}>{itemRunning ? '⟳ Sincronizando...' : '＋ Agregar y sincronizar'}</button></div><div className="one-log-head"><div><h2>Log de sincronización</h2><span>{itemLogs.length ? `${itemLogs.length} registros` : 'Sin ejecución reciente'}</span></div><button className="copy-log" onClick={copyItemLogs} disabled={!itemLogs.length}>Copiar log</button></div><div className="process-log">{itemLogs.length ? itemLogs.map((line, i) => <div key={i}>{line}</div>) : <span>Selecciona un ítem o escribe un slug para ver el progreso.</span>}</div></section>
  </main>{selected && <Modal def={selected} params={params} setParams={setParams} close={() => setSelected(null)} execute={() => execute(selected)} executing={executing} />}</div>;
}
function Field({ label, children }: { label: string; children: React.ReactNode }) { return <label className="field"><span>{label}</span>{children}</label>; }
function Combobox({ options, value, onChange, placeholder }: { options: { id: string; title: string }[]; value: string; onChange: (id: string) => void; placeholder?: string }) {
  const [query, setQuery] = useState('');
  const [open, setOpen] = useState(false);
  const ref = useRef<HTMLDivElement>(null);
  useEffect(() => {
    const onDoc = (e: MouseEvent) => { if (ref.current && !ref.current.contains(e.target as Node)) setOpen(false); };
    document.addEventListener('mousedown', onDoc);
    return () => document.removeEventListener('mousedown', onDoc);
  }, []);
  const selected = options.find(o => o.id === value);
  const q = query.toLowerCase();
  const filtered = options.filter(o => !q || `${o.title} ${o.id}`.toLowerCase().includes(q)).slice(0, 250);
  const choose = (id: string) => { onChange(id); setOpen(false); setQuery(''); };
  return <div className="combobox" ref={ref}>
    <input role="combobox" aria-expanded={open} aria-label={placeholder || 'Buscar ítem'} aria-autocomplete="list" value={open ? query : selected ? `${selected.title} · ${selected.id}` : ''} placeholder={placeholder || 'Buscar ítem...'} onFocus={() => { setQuery(''); setOpen(true); }} onChange={e => { setQuery(e.target.value); setOpen(true); }} onKeyDown={e => { if (e.key === 'Enter' && filtered.length && filtered[0].id !== value) choose(filtered[0].id); if (e.key === 'Escape') setOpen(false); if (e.key === 'ArrowDown' && open) e.preventDefault(); }} />
    {open && <div className="combobox-list" role="listbox">{filtered.length ? filtered.map(o => <button key={o.id} type="button" role="option" aria-selected={o.id === value} className={'combobox-option' + (o.id === value ? ' selected' : '')} onClick={() => choose(o.id)}><span>{o.title}</span><small>{o.id}</small></button>) : <div className="combobox-empty">Sin resultados para “{query}”</div>}</div>}
  </div>;
}
function PanelTitle({ title, subtitle }: { title: string; subtitle: string }) { return <div className="panel-head"><div><h2>{title}</h2><span>{subtitle}</span></div></div>; }
function Metric({ title, value, tone }: { title: string; value: number; tone: string }) { return <div className={'metric ' + tone}><span>{title}</span><b>{value}</b><small>Actualizado en vivo</small></div>; }
function StatusBadge({ status }: { status: string }) { return <span className={'badge ' + status}>{status === 'running' ? 'Ejecutando' : status === 'completed' ? 'Completado' : status === 'failed' ? 'Error' : 'Listo'}</span>; }
function Modal({ def, params, setParams, close, execute, executing }: { def: Def; params: Record<string, string | boolean>; setParams: React.Dispatch<React.SetStateAction<Record<string, string | boolean>>>; close: () => void; execute: () => void; executing: boolean }) { return <div className="modal-backdrop" onClick={close}><div className="modal-card" onClick={e => e.stopPropagation()}><button className="modal-close" onClick={close}>×</button><h2>{def.label}</h2>{def.fields?.includes('pages') && <><Field label="Páginas (ej: 1-20 o 1,3,5)"><input type="text" value={String(params.pages)} onChange={e => setParams(v => ({ ...v, pages: e.target.value }))} /></Field><label className="switch-row"><input type="checkbox" checked={params.replace === true} onChange={e => setParams(v => ({ ...v, replace: e.target.checked }))} /> Reemplazar datos</label></>}<button className="primary-button" onClick={execute} disabled={executing}>{executing ? '⟳ Ejecutando...' : '▶ Ejecutar'}</button></div></div>; }

function M3UImportPanel({ url, setUrl, preview, sel, setSel, search, setSearch, msg, loading, onLoad, onImport }: { url: string; setUrl: (v: string) => void; preview: M3uCh[]; sel: number[]; setSel: (v: number[]) => void; search: string; setSearch: (v: string) => void; msg: string; loading: boolean; onLoad: () => void; onImport: () => void }) { const q = search.toLowerCase(); const filtered = preview.filter(c => (c.title + ' ' + c.group + ' ' + c.country).toLowerCase().includes(q)); const allChecked = filtered.length > 0 && filtered.every(c => sel.includes(c.idx)); const toggle = (idx: number) => setSel(sel.includes(idx) ? sel.filter(x => x !== idx) : [...sel, idx]); const toggleAll = () => setSel(allChecked ? sel.filter(x => !filtered.some(c => c.idx === x)) : Array.from(new Set([...sel, ...filtered.map(c => c.idx)]))); return <div className="m3u-panel"><div className="gitem-row"><Field label="URL de la lista M3U"><input value={url} onChange={e => setUrl(e.target.value)} placeholder="https://iptv-org.github.io/iptv/index.m3u" onKeyDown={e => { if (e.key === 'Enter') onLoad(); }} /></Field><button className="primary-button" onClick={onLoad} disabled={loading}>{loading ? '⟳ Cargando...' : '📡 Cargar lista'}</button></div>{msg && <div className="form-message">{msg}</div>}{preview.length > 0 && <><div className="gitem-row"><Field label="Buscar canal"><input value={search} onChange={e => setSearch(e.target.value)} placeholder="Filtrar por nombre, grupo o país..." /></Field></div><div className="m3u-head"><strong>{filtered.length} / {preview.length} canales</strong><label className="bk-col m3u-all"><input type="checkbox" checked={allChecked} onChange={toggleAll} /> Todos los visibles</label></div><div className="m3u-list">{filtered.map(c => <label className="bk-col" key={c.idx}><input type="checkbox" checked={sel.includes(c.idx)} onChange={() => toggle(c.idx)} />{c.logo && <img className="m3u-logo" src={c.logo} alt="" />}<span className="m3u-title">{c.title}</span><small className="m3u-meta">{(c.group || '') + (c.country ? ' · ' + c.country : '')}</small></label>)}</div><div className="gitem-row"><button className="primary-button" onClick={onImport} disabled={loading || !sel.length}>{loading ? '⟳ Trabajando...' : `▶ Importar seleccionados (${sel.length})`}</button></div></>}</div>; }
function ProviderLogs({ provider, threads }: { provider: string; threads: Record<string, string[]> }) { const ids = Object.keys(threads); const [active, setActive] = useState(''); const current = active && threads[active] ? active : ids[ids.length - 1]; const copy = () => navigator.clipboard?.writeText((threads[current] || []).join('\n')); return <details className="provider-log"><summary>Logs de {pretty(provider)} <span>{ids.length} hilos</span></summary>{ids.length ? <><div className="thread-toolbar"><div className="thread-tabs">{ids.map((id, i) => { const hasError = threads[id].some(line => /error|fall[oó]|failed|exception/i.test(line)); return <button className={`${id === current ? 'active ' : ''}${hasError ? 'failed' : 'ok'}`} onClick={() => setActive(id)} key={id}>Hilo {i + 1}<span className="thread-state">{hasError ? '!' : '✓'}</span></button>; })}</div><button className="copy-log" onClick={copy}>Copiar</button></div><div className="thread-log">{threads[current].map((line, i) => <div key={i}>{line}</div>)}</div></> : <div className="log-empty">Sin ejecuciones todavía</div>}</details>; }
createRoot(document.getElementById('root')!).render(<React.StrictMode><App /></React.StrictMode>);
